### ISSUE TITLE
Port over best tip selection algorithm to TypeScript

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/Archive-Node-API#7]
To have a good way of selecting the best tip among multiple blocks at the tip of the network, we need to implement a selection algorithm. We can port over the current algorithm here in TypeScript to do so: https://github.com/MinaProtocol/mina/blob/bff1e117ae4740fa51d12b32736c6c63d7909bd1/src/lib/consensus/proof_of_stake.ml#L2950

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @bkase

**Comment by MartinMinkov** [comment]
This cannot be implemented now as `last_vrf_output` and `sub_window_densities` are missing from the Archive Node schema. This will have to wait until changes to the Archive Node schema are made.

**Comment by MartinMinkov** [comment]
Changes to incorporate the data is located here: https://github.com/MinaProtocol/mina/pull/12750#pullrequestreview-1320464364

**Comment by MartinMinkov** [comment]
With the new [Berkeley redeployment](https://github.com/MinaProtocol/mina/releases/tag/2.0.0rampup1-b1facec), this is now actionable and ready to implement :partying_face:

**Comment by shimkiv** [comment]
@MartinMinkov should this one fix an issue when Archive-Node-API returned duplicated data for the short period of time because of the chain reorg?
Example, create zkapp txn with events/actions in env. where forks are more frequent ([light network](https://github.com/MinaProtocol/mina/pull/13287)), then wait until it will be added into the block and query Archive-Node-API for events/actions. In case when forks are more frequent API will return duplicated data within the time period required to settle the best tip within the network, after which API will return data without duplicates.
